[theme]
primaryColor="#D71E28"  # Your red color rgb(215, 30, 40)
backgroundColor="#FFFFFF"  # White background
secondaryBackgroundColor="#F0F2F6"  # Light gray for sidebars/secondary elements
textColor="#262730"  # Dark text color
font="sans serif"  # Font family
